### ISSUE TITLE
Illustrations in entry "Function Calls, Word Alignment, and Interrupts on a TI DSP"

### ISSUE THREAD

**Issue by deinonychus** [ScottMansfield/blog#1]
In above mentioned blog entry both pictures _TI-DSP-Stack-Misalignment.png_ and _TI-DSP-Stack-Misalignment-fix.png_ are identical.

**Comment by ScottMansfield** [comment]
Hey, thanks for the issue. It slipped by since I track a bunch of repositories and stopped getting email (because it was too spammy). I'm taking a look at this.

**Comment by ScottMansfield** [comment]
Fixed. Thanks for the report @deinonychus
